

# 日志设置
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  file:
#    name:  sell.log
#    path:  ${catalina.base:-.}/logs
#  level:  #可以指定类
#    root: debug

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Lbj19841230

    url: jdbc:mysql://rm-bp1z8e736h17ic2n2ao.mysql.rds.aliyuncs.com/res?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
