

# 日志设置
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  file:
#    name:  sell.log
#    path:  ${catalina.base:-.}/logs
#  level:  #可以指定类
#    root: debug

server:
  servlet:
    context-path: /sell

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Lbj19841230

    url: jdbc:mysql://rm-bp1z8e736h17ic2n2ao.mysql.rds.aliyuncs.com/res?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true

  jackson:
    default-property-inclusion: non_null


wechat:
  # 公众账号, 授权
  mpAppId: wxd898fcb01713c658
  mpAppSecret:

  # 开放平台,  卖家扫码登录用
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9xxxxxx

  # 支付/商户号
  mchId: 1483469312
  mchKey: 06C56A89949D617xxxxxxxxxxx
  # 发起支付不需要证书, 退款需要
  keyPath:
  notifyUrl: http://sell.natapp4.cc/sell/pay/notify
  templateId:
    orderStatus: e-Cqq67QxD6YNI41iRiqawEYdFavW_7pc7LyEMb-yeQ

projectUrl:
  wechatMpAuthorize: http://lsx888.natapp1.cc
  wechatOpenAuthorize: http://lsx888.natapp1.cc
  sell: http://lsx888.natapp1.cc
